pipeline {
    agent any
    environment {
        AWS_DEFAULT_REGION="us-east-1"     
    }
        
    stages {
        stage('Infrastructure Deployment') {
           environment {
             AWS_ACCESS_KEY_ID = credentials('aws_access_key_id')
             AWS_SECRET_ACCESS_KEY = credentials('aws_secret_access_key')

             TF_REGION = credentials('tf_region')
             TF_AZ = credentials('tf_az')
             TF_MY_IP = credentials('tf_my_ip')
             TF_INSTANCE_TYPE = credentials('tf_instance_type')
             TF_KP = credentials('tf_kp')
             

           }
           steps {
              script {
                  // Write tfvars from Jenkins credentials
                    writeFile file: 'App_EC2/terraform.tfvars', text: """
                    region        = "${env.TF_REGION}"
                    az           = "${env.TF_AZ}"
                    my_ip    = "${env.TF_MY_IP}"
                    instance_type = "${env.TF_INSTANCE_TYPE}"
                    kp            = "${env.TF_KP}"
                    
                    """

                    sh """
                        cd App_EC2
                        terraform init
                        terraform validate
                        terraform plan -var-file=terraform.tfvars
                        terraform ${action} -var-file=terraform.tfvars --auto-approve
                    """
            }
        }
               
     }
    }
    
}